def menu():
    print("--" * 30)
    print("<< MENU PRINCIPAL >>".center(60))
    print("--" * 30)
    print("[1] Registrar mesa   🍽️")
    print("[2] Tomar mozo       👨")
    print("[3] Tomar pedido     🍔")
    print("[4] Calcular pago    💵")
    print("[5] Finalizar pedido 🍽️")
    print("[6] Ver reportes     📈")
    print("[7] Salir  ")
    print("--" * 30)
    print("<< ...SISTEMA RESTAURANTE -- BIENVENIDOS ...>>".center(60))
    print("--" * 30)
menu()